// Set up indexes in MongoDB
db.ip.createIndex({"events_meta.total":-1},{background: true})
db.ip.createIndex({"geo.ctry":1},{background: true})
db.ip.createIndex({"as_maxmind.num":1},{background: true})
db.ip.createIndex({"as_rv.num":1},{background: true})
db.ip.createIndex({"ts_added":-1},{background: true})
db.ip.createIndex({"ts_last_update":-1},{background: true})
db.ip.createIndex({"ts_last_event":-1},{background: true})
db.ip.createIndex({"hostname":1},{background: true})
db.ip.createIndex({"bl": 1},{partialFilterExpression: {"bl": {$exists: true}}, background: true} )
db.ip.createIndex({"rep":-1},{background: true})
db.ip.createIndex({"bgppref":1},{background: true})
db.ip.createIndex({"ipblock":1},{background: true})
db.ip.createIndex({"_nru4h": 1},{background: true})
db.ip.createIndex({"_nru1d": 1},{background: true})
db.ip.createIndex({"_nru1w": 1},{background: true})
db.asn.createIndex({"_nru4h": 1},{background: true})
db.asn.createIndex({"_nru1d": 1},{background: true})
db.asn.createIndex({"_nru1w": 1},{background: true})
db.asn.createIndex({"org":1},{background: true})
db.ipblock.createIndex({"org":1},{background: true})
