#!/bin/bash

if [[ "$1" == "config" ]]; then
cat <<EOF
graph_title Shodan InternetDB module
graph_category nerd
graph_vlabel API requests by result (per 5 min)

add_or_update_data.label add_or_update_data
add_or_update_data.draw AREASTACK
no_data.label no_data
no_data.draw AREASTACK
remove_old_data.label remove_old_data
remove_old_data.draw AREASTACK
rate_limit.label rate_limit
rate_limit.draw AREASTACK
skipped.label skipped
skipped.draw AREASTACK
unexpected_reply.label unexpected_reply
unexpected_reply.draw AREASTACK
EOF
exit 0
fi

ecl_reader /etc/nerd/event_logging.yml -g shodan -i 5m | sed -E 's/:([0-9]+)$/.value \1/'

