#!/bin/sh

if [ "$1" == "config" ]; then
  cat <<'END'
graph_title Event processing delay
graph_info Difference between current time and time of the latest processed event.
graph_category nerd
graph_vlabel Delay [minutes]
graph_scale no
delay.label delay
delay.warn 30
END
  exit 0
fi

echo "delay.value $(mongo nerd --quiet --eval 'print((ISODate().getTime() - db.ip.find({}, {last_activity: 1, _id: 0}).sort({last_activity: -1}).limit(1).next().last_activity.getTime())/60000)')"
