#!/bin/sh

if [ "$1" == "config" ]; then
  cat <<'END'
graph_title Number of entities in database
graph_category nerd
graph_vlabel Number of entities
ip.label Number of IPs
bgppref.label Number of BGP prefixes
ipblock.label Number of IP blocks
asn.label Number of ASNs
org.label Number of Organizations
END
  exit 0
fi

# grep is used because mongosh puts an empty line at the end that we don't want there
mongosh nerd --quiet --eval "
  print('ip.value', db.ip.count());
  print('bgppref.value', db.bgppref.count());
  print('ipblock.value', db.ipblock.count());
  print('asn.value', db.asn.count());
  print('org.value', db.org.count());
" | grep -v "^$"

