#!/bin/bash

if [ "$1" == "config" ]; then
  cat <<'END'
graph_title Number of entities in database
graph_category nerd
graph_vlabel Number of entities
ip.label Number of IPs
bgppref.label Number of BGP prefixes
ipblock.label Number of IP blocks
asn.label Number of ASNs
org.label Number of Organizations
END
  exit 0
fi

# grep is used because mongosh puts an empty line at the end that we don't want there
mongosh "$(cat /etc/nerd/mongodb_credentials)" --quiet --eval "
  print('ip.value', db.ip.estimatedDocumentCount());
  print('bgppref.value', db.bgppref.estimatedDocumentCount());
  print('ipblock.value', db.ipblock.estimatedDocumentCount());
  print('asn.value', db.asn.estimatedDocumentCount());
  print('org.value', db.org.estimatedDocumentCount());
" | grep -v "^$"

